<?php

/**
 * BaseFamily
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $description
 * @property string $pic
 * @property clob $link
 * @property string $contact_mail
 * @property int $type_family
 * @property Doctrine_Collection $Products
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method clob                getDescription()  Returns the current record's "description" value
 * @method string              getPic()          Returns the current record's "pic" value
 * @method clob                getLink()         Returns the current record's "link" value
 * @method string              getContactMail()  Returns the current record's "contact_mail" value
 * @method int                 getTypeFamily()   Returns the current record's "type_family" value
 * @method Doctrine_Collection getProducts()     Returns the current record's "Products" collection
 * @method Family              setName()         Sets the current record's "name" value
 * @method Family              setDescription()  Sets the current record's "description" value
 * @method Family              setPic()          Sets the current record's "pic" value
 * @method Family              setLink()         Sets the current record's "link" value
 * @method Family              setContactMail()  Sets the current record's "contact_mail" value
 * @method Family              setTypeFamily()   Sets the current record's "type_family" value
 * @method Family              setProducts()     Sets the current record's "Products" collection
 * 
 * @package    bwrecords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFamily extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('family');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('pic', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('contact_mail', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('type_family', 'int', 1, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 1,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Product as Products', array(
             'local' => 'id',
             'foreign' => 'family_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable();
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}