<?php

/**
 * Basecomment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nick
 * @property clob $message
 * @property boolean $is_approved
 * @property integer $news_id
 * @property news $news
 * 
 * @method string  getNick()        Returns the current record's "nick" value
 * @method clob    getMessage()     Returns the current record's "message" value
 * @method boolean getIsApproved()  Returns the current record's "is_approved" value
 * @method integer getNewsId()      Returns the current record's "news_id" value
 * @method news    getNews()        Returns the current record's "news" value
 * @method comment setNick()        Sets the current record's "nick" value
 * @method comment setMessage()     Sets the current record's "message" value
 * @method comment setIsApproved()  Sets the current record's "is_approved" value
 * @method comment setNewsId()      Sets the current record's "news_id" value
 * @method comment setNews()        Sets the current record's "news" value
 * 
 * @package    bwrecords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecomment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('nick', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('message', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('is_approved', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             ));
        $this->hasColumn('news_id', 'integer', 8, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 8,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('news', array(
             'local' => 'news_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}