<?php

/**
 * Baserelease
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $family_id
 * @property string $name
 * @property clob $tracklist
 * @property string $release_date
 * @property string $pic
 * @property clob $description
 * @property string $soundcloud
 * @property string $prix
 * @property family $family
 * 
 * @method integer getFamilyId()     Returns the current record's "family_id" value
 * @method string  getName()         Returns the current record's "name" value
 * @method clob    getTracklist()    Returns the current record's "tracklist" value
 * @method string  getReleaseDate()  Returns the current record's "release_date" value
 * @method string  getPic()          Returns the current record's "pic" value
 * @method clob    getDescription()  Returns the current record's "description" value
 * @method string  getSoundcloud()   Returns the current record's "soundcloud" value
 * @method string  getPrix()         Returns the current record's "prix" value
 * @method family  getFamily()       Returns the current record's "family" value
 * @method release setFamilyId()     Sets the current record's "family_id" value
 * @method release setName()         Sets the current record's "name" value
 * @method release setTracklist()    Sets the current record's "tracklist" value
 * @method release setReleaseDate()  Sets the current record's "release_date" value
 * @method release setPic()          Sets the current record's "pic" value
 * @method release setDescription()  Sets the current record's "description" value
 * @method release setSoundcloud()   Sets the current record's "soundcloud" value
 * @method release setPrix()         Sets the current record's "prix" value
 * @method release setFamily()       Sets the current record's "family" value
 * 
 * @package    bwrecords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baserelease extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('release');
        $this->hasColumn('family_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tracklist', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('release_date', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('pic', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('soundcloud', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('prix', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('family', array(
             'local' => 'family_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}