<?php

/**
 * commentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class commentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object commentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('comment');
    }
}