<?php

/**
 * Contact
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bwrecords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Contact extends BaseContact
{
    const TYPE_CONTACT = 1;
    const TYPE_DEMO = 2;
    const TYPE_GRA = 3;
    const TYPE_PHO = 4;

    public static function getType() {
        return array(self::TYPE_CONTACT => "Contact/Booking",  self::TYPE_DEMO => "Demo/Remix",  self::TYPE_GRA => "Direction artistique graphisme",  self::TYPE_PHO => "Direction artistique photographie");
    }
}
