<?php

/**
 * Family
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bwrecords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Family extends BaseFamily
{
    const TYPE_ART = 1;
    const TYPE_PHO = 2;
    const TYPE_GRA = 3;

    public static function getType() {
        return array(self::TYPE_ART => "Artistes", self::TYPE_PHO => "Photographes", self::TYPE_GRA => "Graphistes");
    }
}