<?php

/**
 * familyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class familyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object familyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('family');
    }
}