<?php

/**
 * FamilyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FamilyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FamilyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Family');
    }
}