<?php

/**
 * newsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class newsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object newsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('news');
    }
}