<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    bwrecords
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
    const TYPE_RELEASE = 1;
    const TYPE_MERC = 2;

    public static function getType() {
        return array(self::TYPE_RELEASE => "Releases", self::TYPE_MERC => "Merchandising");
    }

}