<?php

/**
 * releaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class releaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object releaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('release');
    }
}