# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        BRAIN WASHER RECORDS
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, CSS1.css]

  javascripts:    [jquery-1.7.4.min.js,menu.js]

  has_layout:     true
  layout:         layout
