detect_relations: true

options:
 collate: utf8_unicode_ci
 charset: utf8
 
Article:
 actAs:
  Timestampable: ~
 tableName:     article
 columns:
  title: { type: string(255), notnull: true }
  body:  { type: clob, notnull: true }
  pic:   { type: string(255), notnull: true }
 relations:
  Comments:
   class:        Comment
   local:        id
   foreign:      article_id
   type:         many

Comment:
 actAs:
  Timestampable: ~
 tableName: comment
 columns:
  nick:         { type: string(255), notnull: true }
  message:      { type: clob, notnull: true }
  is_approved:  { type: boolean, default: false, notnull: true }
  article_id:   { type: integer(8), notnull: true }
 relations:
  Article:
   local:         article_id
   foreign:       id
   onDelete:      cascade

Family:
 actAs:
   Timestampable: ~
 tableName: family
 columns:
  name: { type: string(255), notnull: true }
  description: { type: clob, notnull: true }
  pic: { type: string(255), notnull: true }
  link: { type: clob, notnull: true }
  contact_mail: { type: string(255), notnull: false }
  type_family: { type: int(1), notnull: true }
 relations:
  Products:
   class:        Product
   local:        id
   foreign:      family_id
   type:         many

Product:
 actAs:
  Timestampable: ~
 tableName: product
 columns:
  name: { type: string(255), notnull: true }
  tracklist: { type: clob, notnull: true }
  release_date: { type: string(255), notnull: true }
  pic: { type: string(255), notnull: true }
  description: { type: clob, notnull: true }
  soundcloud: { type: string(255), notnull: true }
  prix: { type: string(255), notnull: true }
  family_id: { type: integer, notnull: true }
 relations:
  Family:
   local:    family_id
   foreign:  id
   onDelete: cascade
